# Sitio Jekyll sin temas (NO usar themes)
title: "Liroy Cataldo - Estudiante de Ciencia de Datos"
description: "Sitio Jekyll construido sin temas predefinidos"
baseurl: "/web_page" # importante porque est치 en subcarpeta
url: "https://lirbast.github.io"
theme: null

markdown: kramdown
permalink: /:categories/:title/

# Configuraci칩n b치sica de Jekyll

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page:num/"

# El plugin jekyll-paginate es incluido autom치ticamente en GitHub Pages